### ISSUE TITLE
Use Nuget instead of Git submodule for C# API

### ISSUE THREAD

**Issue by vania-pooh** [allure-framework/allure-mstest#3]
Not sure how it works but NUnit adapter doesn't use Git submodule. Please look at https://github.com/allure-framework/allure-nunit and try to eliminate submodules. I have really bad experience with them.

**Comment by vishwas20** [comment]
AllureCharpCommons is missing in the reference, project is failing, Trying to fix it but failed to do so.

**Comment by Bakanych** [comment]
Hi @vishwas20,
this version of allure adapter is not supported at this moment. Can you consider to migrate to Allure 2?
Currently it's possible to generate report directly from trx file using Allure CLI.
